apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resources
  labels:
    app: resources
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resources
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: lifecycle
          image: localhost:5000/resources
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.5"
            limits:
              memory: "0.75Gi"
              cpu: "1"
