apiVersion: v1
kind: Service
metadata:
  namespace: hades
  name: namespaces-app2
spec:
  type: NodePort
  ports:
  - name: namespaces-app2
    port: 8080
    targetPort: 8080
  selector:
    app: namespaces-app2