apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namespaces-app1
  labels:
    app: namespaces-app1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: namespaces-app1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: namespaces-app1
          image: localhost:5000/namespaces-app1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

