apiVersion: v1
kind: Service
metadata:
  name: share-stuff
spec:
  type: NodePort
  ports:
  - name: share-stuff-app1
    port: 8080
    targetPort: 8080
  - name: share-stuff-app2
    port: 8081
    targetPort: 8081
  selector:
    app: share-stuff