apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dns-app1
  labels:
    app: dns-app1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-app1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: dns-app1
          image: localhost:5000/dns-app1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

